// Generate src/components/icons.ts from the Material Symbols SVG set.
//
// Why not the icon font: the full outlined woff2 is 3.8 MB for thousands of
// glyphs and this app uses about twenty-five. Subsetting it does not work
// cleanly -- the font resolves icon names through chained `rclt`/`rlig`
// substitutions that fontTools' closure cannot narrow, so a subset either drops
// the icons or keeps nearly all of them. Since web/dist is committed so that
// `fath web` needs no node, a 3.8 MB binary would land in git and re-churn on
// every rebuild.
//
// Inlining the paths instead costs about 6 kB, needs no font loading, and
// cannot fail on a slow connection.
//
// The icon list is scanned out of the source, so it cannot drift from what the
// components actually ask for.
//
//   node scripts/build-icons.mjs

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const svgDir = join(root, "node_modules", "@material-symbols", "svg-400", "outlined");
const target = join(root, "src", "components", "icons.ts");

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

// Two passes with different confidence.
//
// Required: anything written as name="check" or icon="check". A missing SVG for
// one of those is a real bug and fails the build.
//
// Candidate: every other lowercase_underscore string literal in the source,
// kept only when an SVG of that name actually exists. That looseness is
// deliberate -- icons are also chosen in ternaries (`name={ok ? "check_circle"
// : "error"}`) and in lookup tables, and an attribute-only scan silently
// produced blank icons for those. Validating against the SVG set is what makes
// the loose pass safe: `cost: "free"` matches the pattern but has no icon, so
// it is simply dropped.
const required = new Set();
const candidates = new Set();
for (const file of walk(join(root, "src"))) {
  if (!/\.tsx?$/.test(file) || file.endsWith("icons.ts")) continue;
  const text = readFileSync(file, "utf8");
  for (const match of text.matchAll(/(?:name|icon)="([a-z_0-9]+)"/g)) required.add(match[1]);
  for (const match of text.matchAll(/"([a-z][a-z_0-9]{2,})"/g)) candidates.add(match[1]);
}

const wanted = [...new Set([...required, ...candidates])].sort();
if (wanted.length === 0) throw new Error("found no icon names - refusing to write an empty set");

const entries = [];
const missing = [];
for (const name of wanted) {
  const file = join(svgDir, `${name}.svg`);
  let svg;
  try {
    svg = readFileSync(file, "utf8");
  } catch {
    if (required.has(name)) missing.push(name);
    continue;
  }
  // Every icon in this set is a single <path> on the same 0 -960 960 960 grid,
  // so the path data alone is enough and the component supplies the wrapper.
  const path = svg.match(/ d="([^"]+)"/)?.[1];
  if (!path) {
    if (required.has(name)) missing.push(name);
    continue;
  }
  entries.push(`  "${name}": "${path}",`);
}

if (missing.length) {
  throw new Error(
    `no SVG for: ${missing.join(", ")}\n` +
      "Check the name against https://fonts.google.com/icons (outlined, weight 400).",
  );
}

const output = `// GENERATED by scripts/build-icons.mjs -- do not edit by hand.
//
// Only the icons this app uses, inlined as path data. Regenerate after adding
// an icon:  npm run icons
//
// Source: @material-symbols/svg-400 (outlined), viewBox "0 -960 960 960".

export const ICON_PATHS: Record<string, string> = {
${entries.join("\n")}
};

export type IconName = keyof typeof ICON_PATHS;
`;

writeFileSync(target, output, "utf8");
console.log(`wrote ${entries.length} icons to src/components/icons.ts`);
console.log(entries.map((e) => e.match(/"([^"]+)"/)[1]).join(" "));
